apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-service-without-fixed-ip
  name: sample-service-without-fixed-ip
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample
  type: LoadBalancer

